### ISSUE TITLE
BUG: Slider block image focal point can't be changed

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1316]
## Context

After a slider block has been created, changing the focal point doesn't save.

This ONLY seems to be happening with slider block images. Images added to basic pages, content grids are saving the focal point changes.

## Cause

Focal point changes not saved when editing translatable fields
https://www.drupal.org/node/2901333

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Blocks
3. Click Add Block
4. Click Slider
5. Click save
6. Click Edit
7. Change focal point

## Expected result

The changed focal point setting should be saved

## Current result

The changes are not saved

**Comment by jeor0980** [comment]
I added the suggested patch to the bug/1316 branch but it breaks atlas when building a new site locally giving the following error. 
`Requested: drush site-install -y express
Executed: /bin/bash -l -c "cd /data/releases/p16f53e20613/current >/dev/null && drush site-install -y express"
[2017-08-31 19:41:08,801: WARNING/Worker-2] Aborting.
[2017-08-31 19:41:10,037: ERROR/MainProcess] Task atlas.tasks.site_provision[b3e0bae3-442f-4085-a2d3-a4c3d7c59456] raised unexpected: WorkerLostError('Worker exited prematurely: exitcode 0.',)
Traceback (most recent call last):
  File "/data/environments/atlas/lib/python2.7/site-packages/billiard/pool.py", line 1175, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: exitcode 0.
==> /var/log/celery/w3.log <==
[2017-08-31 19:44:09,828: WARNING/Worker-1] PHP Fatal error:  Cannot use object of type EntityStructureWrapper as array in /data/code/profiles/express/express-2.61/modules/contrib/focal_point/focal_point.module on line 289
[2017-08-31 19:44:09,828: WARNING/Worker-1] [express.local] out:
[2017-08-31 19:44:09,828: WARNING/Worker-1] [express.local] out:
[2017-08-31 19:44:09,828: WARNING/Worker-1] Fatal error: Cannot use object of type EntityStructureWrapper as array in /data/code/profiles/express/express-2.61/modules/contrib/focal_point/focal_point.module on line 289
[2017-08-31 19:44:09,828: WARNING/Worker-1] [express.local] out:
[2017-08-31 19:44:09,828: WARNING/Worker-1] Drush command terminated abnormally due to an unrecoverable error.       [error]
[2017-08-31 19:44:09,829: WARNING/Worker-1] [express.local] out:
[2017-08-31 19:44:09,829: WARNING/Worker-1] Error: Cannot use object of type EntityStructureWrapper as array in
[2017-08-31 19:44:09,829: WARNING/Worker-1] [express.local] out:
[2017-08-31 19:44:09,829: WARNING/Worker-1] /data/code/profiles/express/express-2.61/modules/contrib/focal_point/focal_point.module,
[2017-08-31 19:44:09,829: WARNING/Worker-1] [express.local] out:
[2017-08-31 19:44:09,829: WARNING/Worker-1] line 289
[2017-08-31 19:44:09,829: WARNING/Worker-1] [express.local] out:
[2017-08-31 19:44:09,939: DEBUG/Worker-1] [chan 36] EOF received (36)
[2017-08-31 19:44:09,940: DEBUG/Worker-1] [chan 36] EOF sent (36)
[2017-08-31 19:44:09,946: WARNING/Worker-1] Fatal error: run() received nonzero return code 255 while executing!
Requested: drush site-install -y express
Executed: /bin/bash -l -c "cd /data/releases/p145b0934f08/current >/dev/null && drush site-install -y express"
[2017-08-31 19:44:09,946: WARNING/Worker-1] Aborting.
[2017-08-31 19:44:14,427: ERROR/MainProcess] Task atlas.tasks.site_provision[8b83b6c5-0643-4d29-ba1d-1fbcea9f5c65] raised unexpected: WorkerLostError('Worker exited prematurely: exitcode 0.',)
Traceback (most recent call last):
  File "/data/environments/atlas/lib/python2.7/site-packages/billiard/pool.py", line 1175, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: exitcode 0.`

**Comment by cathysnider** [comment]
This is still a bug 
https://www-dev.colorado.edu/p149ac453e4a/

**Comment by cathysnider** [comment]
Acceptance Criteria:
-  [ ] focal points can be changed on sliders
 - [ ] focal points can be changed on sliders that were created before the update was implemented
